import 'package:flutter/material.dart';
import 'model/category.dart';
import 'model/content.dart';

var CategoriesData = [
  Category("Biologia", Color.fromRGBO(220, 251, 209, 2), Image.asset('assets/biology.png'), Content("Biologia", Image.asset('assets/biologist.png'), 'Sou formada em Ciências Biológicas pela Universidade Federal do Rio Grande do Sul (UFRGS). Porém, após ter várias experiências com Empreendedorismo e Inovação, '
  'percebi que não queria atuar como bióloga e resolvi migrar para uma área que me permitisse exercitar minha criatividade e liderança, além de pôr em prática minhas ideias.', Color.fromRGBO(144, 200, 124, 1))),
  Category("Voluntária", Color.fromRGBO(255, 219, 225, 2), Image.asset("assets/volunteer.png"), Content("Voluntariado", Image.asset('assets/sos.png'), 'Em 2018 entrei para a ENACTUS, uma organização internacional que auxilia comunidades a se desenvolverem pelo empreendedorismo social. Lá, fiz trabalho voluntário junto à'
      ' SOS Casas de Acolhida, casas de acolhimento em Porto Alegre e Canoas, no Rio Grande do Sul, que recebem crianças e adolescentes vítimas de violência e negligência. Assim, criamos o projeto Heley, que recebeu menção honrosa no prêmio “Ozires Silva” em 2020.', Colors.pinkAccent)),
  Category("Pets", Color.fromRGBO(226, 226, 226, 2), Image.asset("assets/pets.png"), Content("Meus Pets", Image.asset('assets/cats.png'), 'Eu amo animais e quando estava cursando biologia pensava em ir para a área de Zoologia, porém acabei só com meus filhos felinos mesmo. Esses são o Pepe Le Piu (o gato frajola com atitude) e a Princesa Zelda(a gata pretinha que é fofinha, mas bagunça muito!).', Colors.grey)),
  Category("Leitura", Color.fromRGBO(193, 240, 255, 2), Image.asset("assets/books.png"), Content("Meta de Leitura", Image.asset('assets/reading.png'), 'Um dos meus Hobbies preferidos é ler. Em 2020 antes da pandemia resolvi retomá-lo e fui muito bem sucedida, tenho o hábito de ler livros físicos e ebooks, além de ouvir audiobooks também. \n Meta de Leitura 2020: 15 livros lidos.\n Meta de Leitura 2021: 12 livros lidos. \n Meta de Leitura 2022: 27 de 52 livros lidos. \n Em 2022 fui ousada e aumentei a meta para um livro por semana! ',   Color.fromRGBO(45, 174, 215, 2))),
  Category("Alemão", Color.fromRGBO(251, 242, 209, 2), Image.asset("assets/german.png"), Content("Língua Alemã", Image.asset('assets/neuschwanstein.png'), 'Desde o final de 2019 estudo alemão. Não foi a minha primeira opção ao escolher uma terceira língua (além do português nativo e o inglês fluente), mas tenho gostado muito de estudar e já estou no nível "pré-intermediário" (B1.1). Meu sonho é conhecer o Castelo Neuschwanstein, que fica perto de Munique (foto). Ele que inspirou o castelo da Disney!',  Colors.yellow)),
  Category("Inglês", Color.fromRGBO(219, 222, 255, 2), Image.asset("assets/english.png"), Content("Língua Inglesa", Image.asset('assets/world.png'), 'Já conheci pessoas de vários países e saber me comunicar em inglês é maravilhoso! Sempre foi um dos meus sonhos conhecer pessoas de vários lugares e poder trocar experiências com elas (além de cantar no karaokê e fazer petiscos brasileiros para elas comerem hehe). Além disso, muitos livros que eu ouço são totalmente em inglês.',   Color.fromRGBO(147, 154, 211, 2))),
  Category("Portugal", Color.fromRGBO(255, 223, 205, 2), Image.asset("assets/portugal.png"), Content("Portugal", Image.asset('assets/rossio.png'), 'De 21/11/2020 a 21/11/2021 (exatamente um ano, e não foi planejado!) morei em Portugal, na região metropolitana de Lisboa. Eu me apaixonei pelo país e pela capital, já considero minha segunda casa e sinto saudades todos os dias. Recomendo muito a viagem! Eu amo viajar e sempre quis morar fora, foi mais um sonho que pude realizar. Infelizmente morei lá por uma parte da pandemia e não pude visitar os outros países da Europa.',  Colors.deepOrange)),
  Category("Brasil", Color.fromRGBO(205, 255, 246, 2), Image.asset("assets/brazil.png"), Content("Cidadã do Mundo", Image.asset('assets/curitiba.png'), 'Sou gaúcha, natural de Porto Alegre, mas morei por um ano em Portugal (2020/2021) e agora faz quase 1 ano que estou morando em Curitiba. Passei bons anos namorando à distância e fazia o trajeto Porto Alegre-Curitiba quase todo mês. A primeira vez que visitei a cidade foi em 2015 (foto). Gosto de brincar que sou "Cidadã do Mundo", pois hoje em dia posso chamar mais de um lugar de "casa".',  Color.fromRGBO(80, 207, 184, 2))),
  Category("Jogos", Color.fromRGBO(226, 226, 226, 2), Image.asset("assets/games.png"), Content("Jogos", Image.asset('assets/stray.png'), 'Gosto de jogos como LOL, Fall Guys, The Sims, mas desde pequena com internet discada ia jogar no site da Barbie e da Polly. Meu primo tinha instalado um emulador de jogos no computador que eu tinha quando criança e eu jogava Sonic etc. Hoje em dia gosto de jogos de campanha fofinhos também como o Stray (foto), em que ajudamos um gato a encontrar sua família e o Alba, em que uma menina ajuda a recuperar uma reserva natural.',  Colors.black)),
  Category("Exercícios", Color.fromRGBO(255, 219, 245, 2), Image.asset("assets/exercise.png"), Content("Exercícios", Image.asset('assets/training.png'), 'Gosto de me exercitar, mexer o corpo, já fiz muitas atividades (ginástica local, funcional, dança, teatro, academia...). Em Portugal todos os dias após o horário comercial eu e meu marido íamos caminhar/correr na praia, me fazia muito bem. Hoje em dia eu treino na academia (enquanto escuto audiobook hehe) e gosto bastante. Acho importante o exercício mais para nossa saúde mental e física.',  Color.fromRGBO(206, 42, 160, 2))),
];