import 'package:flutter/material.dart';
import 'model/experience.dart';

var XpData = [
  Experience(Image.asset('assets/pucpr.png', fit: BoxFit.cover), '2022 - MONITORIA', 'Atualmente curso Bacharelado em Sistemas de Informação na PUCPR onde sou monitora da disciplina de Raciocínio Algorítmico, que trata do desenvolvimento do pensamento computacional. Além de ser monitora em sala da disciplina de Banco de Dados, que trata do aprendizado em armazenamento de dados.'),
  Experience(Image.asset('assets/diretora.png', fit: BoxFit.cover), '2019 a 2020 - DIRETORA', 'No meu tempo voluntariado à ENACTUS, participei como projetista, auxiliando na criação do projeto Heley, participei do Setor Financeiro, arrecadando dinheiro para podermos concretizar nossos projetos e me tornei Diretora de Comunicação e Marketing, fazendo criação de conteúdo e promoção de eventos.'),
  Experience(Image.asset('assets/enactus.png', fit: BoxFit.cover), '2018 a 2020 - ENACTUS', 'Fiz voluntariado na ENACTUS UFRGS, uma das unidades da ENACTUS Brasil, uma organização internacional sem fins lucrativos, com sede nos Estados Unidos e presença em 35 países, dedicada a inspirar jovens universitários a melhorar o mundo através da Ação Empreendedora.'),
  Experience(Image.asset('assets/nasa.png', fit: BoxFit.cover), '2019 - NASA SPACE APPS CHALLENGE', 'Participei do NASA SPACE APPS Challenge, um hackathon promovido pela NASA e pela Fábrica do Futuro, em Porto Alegre-RS. Nosso projeto se chamada "Tchê Ocean Clean" e visava tornar geradores eólicos marítmos em captores de resíduo plástico flutuante, para auxiliar na limpeza dos oceanos.'),
  Experience(Image.asset('assets/empreendedorismo.png', fit: BoxFit.cover), '2018 - EMPREENDEDORISMO', 'Participei da Maratona de Empreendedorismo da UFRGS e do Torneio Empreendedor da PUCRS. Com projetos de ecobags recicladas de guarda-chuva e um esmalte vegano e com menos químicos, respectivamente. Ganhei destaque na sessão ambiental com meu projeto "Lótus", que propunha a criação do esmalte.'),
  Experience(Image.asset('assets/ibama.png', fit: BoxFit.cover), '2018 - IBAMA', 'Fui estagiária do IBAMA, no CETAS (Centro de Triagem de Animais Silvestres). Lá eu fiz trabalhos administrativos, criei jogos para educação ambiental, participei de buscas e apreensões de animais silvestres comercializados ilegalmente, bem como fiz saídas de campo para estudo.'),
  Experience(Image.asset('assets/pibic.png', fit: BoxFit.cover), '2017 - INICIAÇÃO CIENTÍFICA', 'Fui Bolsista PIBIC no Centro de Ecologia da UFRGS pelo CNPq. Desenvolvi o trabalho "Avaliação da toxicidade e genotoxicidade de sedimentos do Rio Taquari utilizando Allium cepa", e ganhei destaque na sessão de Genética Ambiental/Toxicológica na Jornada de Iniciação Científica da FZB/FEPAM de 2017.'),
];