import 'package:flutter/material.dart';
import 'model/project.dart';

var ProjData = [
  Project(Image.asset('assets/portfolio.png'), 'Meu Portfólio para o ADA', 'Quando decidi me inscrever para a Apple Developer Academy, decidi criar um app em Flutter para estudar e para mostrar meus hobbies, projetos e vivências de uma forma diferente. O design foi todo planejado no Figma, mas claro que ao desenvonvê-lo algumas coisas mudaram.'),
  Project(Image.asset('assets/reciclae.png'), 'Reciclaê CWB', 'O reciclaê surgiu na disciplina de Experiência Criativa de BSI. Criamos um site em HTML e CSS para achar pontos de coleta de resíduos recicláveis em Curitiba. Eu que criei o design e pretendo fazer um app dele e publicar nas lojas do Google/Apple Store.'),
  Project(Image.asset('assets/bookshelf.png'), 'Aplicativo de leitura', 'Eu leio bastante e, junto com pessoas leitoras que conheço, sinto falta de um app para acompanhar minhas leituras. Assim surgiu a ideia desse aplicativo de leitura. Já tenho o design e as ideias de funcionalidades. O design também foi feito no Figma.'),
  Project(Image.asset('assets/rdf.png'), 'Podcast Reunião do Foro', 'O Reunião do Foro é um podcast de divulgação científica que trata de vários assuntos, com bom humor e divertimento. Aborda desde pandemias na história, até a possibilidade da existência de sereias e dragões. Sempre com muita ciência. Está no Spotify e no Instagram em @reuniaodoforo'),
  Project(Image.asset('assets/signo.png'), 'Signo, ecobags de guarda-chuva', 'Ao participar da Maratona de Empreendedorismo da UFRGS pivotei na minha ideia inicial e criei uma startuo de ecobags recicladas de guarda-chuva, vendemos várias bolsas e era uma ideia bem sustentável, porém a parceria que tinha não deu certo e não seguimos com a ideia.'),
  Project(Image.asset('assets/lotus.png'), 'Lótus, esmalte vegano e sustentável', 'Fiz um curso de manicure e comecei a me perguntar o que tinha no esmalte que usamos, pois pinto as unhas toda semana. Assim, veio a ideia de criar a Lótus, uma marca de esmaltes vegana e com menos químicos. Na época esmaltes veganos eram pouco conhecidos, até testei receitas, mas ficou por aí.'),
  Project(Image.asset('assets/reses.png'), 'Rolê Empreendedor e Social 2019', 'Fazendo parte da ENACTUS ajudei a organizar o maior encontro de estudantes universitários da região Sul do Brasil, o "Rolê Empreendedor e Social". Foi um evento com muitas palestras e troca de conhecimentos. Ajudei em toda organização e divulgação do evento que foi em Florianópolis, SC.'),
  Project(Image.asset('assets/education.png'), 'Educação Ambiental', 'Ao estagiar no IBAMA, criei alguns projetos solo para educação ambiental. Usando materiais reciclados (caixas de leite) criei marionetes para contar histórias vindas dos gibis do IBAMA e criei um jogo com papelão e vidros de esmalte para conscientização sobre o tráfico de animais silvestres.'),
  Project(Image.asset('assets/profuturo.png'), 'ProFUTURO', 'Caí de para-quedas no mundo do empreendedorismo, aprendendo muito ao participar de eventos e criar, com outras pessoas, a "PROFUTURO" que buscava conectar estudantes de ensino médio com profissionais de várias áreas para uma decisão bem informada na hora de escolher sua carreira.'),
];